### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by grantmcdermott** [stata2r/stata2r.github.io#7]
Just a brain dump atm. @kylebutts @NickCH-K feel free to add.

### data.table

- [x] #15
- [x]  Append/rbindlist
- [x] froll() (noting Stata package asrol) **Maybe not** not basic enough for the page
- [x] #14
- [x] #13
- [x] date operations (`as.IDate()`, `year()`, `month()`, etc.)
- [x] Standardize Stata commands to remove shortcuts. **Resolved** by [f8775021f0](https://github.com/stata2r/stata2r.github.io/commit/f0e28c22e538b5b927e8cf17cb10ebf8775021f0). Special exceptions for `gen` and `reg` (see below) but otherwise done.
- [x] #16

### fixest

- [x] intro (we should mention `stats::lm()`+ here too)
- [x] #18
- [x] use real-life dataset (the same nycflights14 data)?
- [x] #10
- [x] feglm
- [x] iplot
- [x] #29
- [x] wald()
- [x]  mutli-model estimation
- [x] D-i-D / 2wfe
- [x] Regression table example with more than one regression
- [x] Section on standard R formula syntax, probably with non-i() versions of factors and interactions

### misc

- [x] Make sure all code is code-formatted; code is often delineated with ` markers in places
- [x] Link to the GitHub repo somewhere on the rendered page + an invitation to file issues with suggestions/corrections.
- [x] Speaking of the GH repo. We should add a short README.
- [x] Use full width/span for `text.txt` generated text.
- [x] Expand column width of the side-by-side code blocks?
- [x] #12
- [x] Actually, `ggplot2` / plotting might deserve it's own page but that's a whole lot more work... **Resolved:** Just point people to LOST etc.

**Comment by NickCH-K** [comment]
Thoughts:

**data.table**:

- What needs to be revisited about `reshape`? If we discussed this I forgot it
- Did we determine if there's a `tsfill`/`tidyr::complete()` equivalent in **data.table**?
- Date additions are a good idea.
- [ ] We'd talked about adding `append`/`rbindlist`
- [ ] Standardize Stata commands to remove shortcuts
- [ ] `froll()` (noting Stata package **asrol**)
- [ ] Calculations within a **data.table**

**fixest**

- [ ] `feglm`
- [ ] `iplot`
- [ ] Regression table example with more than one regression
- [ ] Section on standard R formula syntax, probably with non-`i()` versions of factors and interactions

**misc**

- For honorable mentions I think **lubridate**, **stringr**, and **purrr** deserve to be on there. I'm not sure what **estimatr** gets us given that we already have **fixest**. **AER** if only for `linearHypothesis()` (is there still not a friendlier version of this yet? I've never cared for `linearHypothesis()`).
- After that we may want to point out packages dealing with common models that aren't covered by **fixest**, like **lme4** for random effects, and whatever the hottest time series package is these days, it seems to keep changing
- I think a whole page for **ggplot2** would be a bit of overshoot for what we're doing. But we can list it in honorable mentions and then maybe just link out to LOST which already has Stata to R conversion of most of the stuff we'd put on such a page anyway

**Comment by grantmcdermott** [comment]
Some quick replies:

Good call on those other suggestions. I'll add them to the OP.

- RE: reshape. I basically think it will be simpler to do a wide reshape first, since the data are already in "tidy" format. That way you don't have to worry about the manual id variable and can reshape back to long afterwards. We should also mention the ability to do complex, multivariable aggregations as part of the `dcast` call. (It's a killer, but lesser-known data.table feature.) I added a "Bonus" example like this in the grouped collapse section, but no harm in repeating.
- RE: tsfill. I've used [this](https://stackoverflow.com/a/66523199/4115816) SO-suggested function before and it works great. But it might be a hack to add, so Occam's razor just suggest omit?
- I'm not sure I'd single out lubridate over the other tidyverse packages (esp since data.table's date functions give you much of the same functionality, nevermind the namespace conflicts). Same for stringr and purrr. But I might have misunderstood you here.
- RE: `AER:linearHypothesis`. I like and generally prefer `multcomp:ghlt`. One minor downside is it doesn't have a dedicated fixest method, although that's fairly easy to workaround as I do for my ritest port [here](https://github.com/grantmcdermott/ritest/blob/master/R/ritest.R#L500-L513). (Reminds me that I should put in a PR!) But I think this is getting beyond scope now. You're totally right about pointing people to LOST.

**Comment by grantmcdermott** [comment]
BTW: You should be able to edit my OP directly, so feel free to add tasks there (and mark them as done).

**Comment by NickCH-K** [comment]
Good point on reshape and tsfill. I do think that lubridate/stringr/purrr maybe deserve specific mentions when going over the tidyverse, if only because stringr versions of functions are way more Stata-like than base, and purrr is just very handy. Lubridate I think deserves mention more for stuff like +days(), beyond what data.table can do, it just makes date data wildly easier to work with. The namespace stuff is definitely a drag though. 

I'll have to check out multicomp!

**Comment by NickCH-K** [comment]
Finished the misc page. @grantmcdermott let me know if I haven't done **collapse** justice; I've never actually used it.

**Comment by NickCH-K** [comment]
To-do list completed!
